name: 🧪 Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: 🛒 Checkout
      uses: actions/checkout@v3
    - name: 🐍 Set up Python 3.14
      uses: actions/setup-python@v4
      with:
        python-version: '3.14'
    - name: 🧰 Install dependencies
      run: make install IGNORE_VENV=1
    - name: 👮 Lint
      run: make lint
    - name: 🔍 Type check
      uses: jakebailey/pyright-action@v1
      with:
        version: 1.1.317
        python-version: '3.14'
        warnings: true
    - name: 🧪 Test
      run: make tests
